### ISSUE TITLE
Composer a nette/utils 2.5.x

### ISSUE THREAD

**Issue by LHavlicek** [contributte/latte-email#2]
Balíček nelze nainstalovat composerem s nette/utils >= 2.5.x. Omezení je pro nette/utils ~2.4.9. Nevím jak v případě nette/utils 3, ale pro 2.5.x jsem k tomu omezení nenašel důvod -> zdá se, že tam vše funguje. Bylo by možné prověřit závislosti v composer.json?

**Comment by mabar** [comment]
Closed by https://github.com/contributte/latte-email/commit/83cb31936f2304f0db8f7efadd6a8068daf73be1
